version: '3.8'

services:
  app:
    image: flask_app
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: "3"
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace:cached
    command:  bash -c "python3 -m flask db upgrade && python3 -m flask --app ./app.py --debug run --host=0.0.0.0"
    networks:
      - flask_app
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
#    container_name: fask-app
    ports:
      - "80-85:5000" # app port
  db:
    container_name: flask-db
    image: "mysql"
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql
      # setup database
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql


    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 10s
        timeout: 10s
        retries: 5
    networks:
      - flask_app

networks:
  flask_app:
    driver: bridge

volumes:
  db-data:
